# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9bf256a7f8d57413f986fbd2528d6b08854adbcfe77e52097eb0e6547d57da65da1e4d42a6ec2b987f99dc1b0db7c5dc9d6b9b7a1abe3147cf6a43bd1efa93b

test:
  secret_key_base: 00b907a495dd4035badb8d189a69b142ef43b78c9e7c124c2d625306cb48731ff03594b2abdafd64b52108bafd2331986f70e382018286316a3520ed6a2488cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
